/* @source domainer application
**
** Reads protein coordinate files and writes domain coordinate files.
** 
** @author: Copyright (C) Jon Ison (jison@hgmp.mrc.ac.uk)
** @@
**
** This program is free software; you can redistribute it and/or
** modify it under the terms of the GNU General Public License
** as published by the Free Software Foundation; either version 2
** of the License, or (at your option) any later version.
** 
** This program is distributed in the hope that it will be useful,
** but WITHOUT ANY WARRANTY; without even the implied warranty of
** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
** GNU General Public License for more details.
** 
** You should have received a copy of the GNU General Public License
** along with this program; if not, write to the Free Software
** Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
**
*******************************************************************************
**  Application name
**  domainer
**  
**  
**  
**  Summary
**  Reads protein coordinate files and writes domain coordinate files.
**  
**  
**  
**  Input and Output
**  domainer reads a scop classification file and a directory of protein 
**  coordinate files and writes, for each domain in the scop classification 
**  file, domain coordinate files in embl-like and pdb formats.  Each domain 
**  coordinate file contains coordinates for a single scop domain.  The paths 
**  and extensions for the protein (input) and domain (output) coordinate 
**  files are specified by the user.  The scop domain identifier codes are used
**  to name the output files.  A log file for each of the embl-like and pdb 
**  format builds is written.
**  
**  
**   
**  Sister applications
**  A 'scop classification file' contains classification and other data for 
**  domains from the scop database.  The file is in embl-like format and is 
**  generated by scopparse.  Domain sequence information can be added to the 
**  file by using scopseqs.
**  A 'protein coordinate file' contains protein coordinate and other data 
**  extracted from a single pdb file.  The files, generated by pdbparse, are in
**  embl-like format and contain 'cleaned-up' data that is self-consistent and
**  error-corrected.  
**  pdbplus, scopreso, scopseqs, scopalign and siggen use domain coordinate 
**  files as input.
**  
**  
**  
**  Notes
**  Where coordinates for multiple models are given in a protein coordinate 
**  file, the domain coordinate file will contain coordinates for the first 
**  model.  
**  
**  In the rare cases where a domain is comprised of segments from more than 
**  one chain, the data in the domain coordinate file will be presented as 
**  belonging to a single chain with a chain identifier of '.'.  A single 
**  sequence will be given
**  
**  The start and end positions of domains in scop coincide in several cases 
**  to residues which either lack a CA atom or for which coordinates for a 
**  single atom only are given in the pdb file.  To ensure these domains are
**  processed during a domainer run, it is important to use clean protein 
**  coordinate files which have NOT been masked to remove such residues.
**  Otherwise errors of the following type may occur in the log file:
**  //
**  D1QFUL1
**  ERROR Domain end not found in ajXyzCpdbWriteDomain 
**
**  //
**  D1QFUL1
**  ERROR Domain start not found in ajXyzCpdbWriteDomain 
**  
**  
**  
**  
**  Known bugs & warnings
**  Wildcard matching of scop domain start and end points
**  scop treats pdb residue numbers as integers and this is a potential source
**  of error in the domain ranges. It means that domainer (via library calls)
**  must use wild card strings when matching a scop start / end point to the
**  pdb residue number strings.
**  
**  
**  
**  
**  Description
**  This program is part of a suite of EMBOSS applications that directly or 
**  indirectly make use of the protein structure databases pdb and scop.  
**  This program is part of an experimental analysis pipeline described in an
**  accompanying document.  We provide the software in the hope that it will
**  be useful.  The applications were designed for specific research purposes
**  and may not be useful or reliable in contexts other than the described 
**  pipeline.  The development of the suite was coordinated by Jon Ison to
**  whom enquiries and bug reports should be sent (email jison@hgmp.mrc.ac.uk).
**  
**  There is a need for a convenient source of protein coordinate data which 
**  includes protein strucutral domain definitions and is therefore appropriate 
**  for domain-centred approaches.  domainer reads protein coordinate files and
**  writes files of coordinate data for individual scop domains in embl-like 
**  and pdb formats.
**  
**  
**  
**  Algorithm
**  
**  
**  
**  Usage
**  An example of interactive use of domainer is shown below.
**
**  Unix % domainer
**  Reads protein coordinate files and writes domain coordinate files.
**  Name of scop classification file (embl format input): /test_data/all.scop
**  Location of protein coordinate files (embl format input) [./]: /test_data/        
**  Extension of protein coordinate files (embl format) [.pxyz]: 
**  Location of domain coordinate files (embl format output) [./]: /test_data/        
**  Extension of domain coordinate files (embl format) [.pxyz]: .dxyz
**  Location of domain coordinate files (pdb format output) [./]: /test_data/        
**  Extension of coordinate files (pdb format) [.ent]: .dent
**  Name of log file for the embl format build [domainer_embl.log]: /test_data/domainer_embl.log
**  Name of log file for the pdb format build [domainer_pdb.log]: /test_data/domainer_pdb.log
**  D1II7A_
**  D1CS4A_
**  Unix % 
**  
**  Protein coordinate files with the file extension .pxyz were read from 
**  /test_data/. Domain definitions were taken from 
**  /test_data/all.scop and domain coordinate files in 
**  embl-like (d1cs4a_.dxyz and d1ii7a_.dxyz) and pdb formats (d1cs4a_.dent  
**  and d1ii7a_.dent) were written.  Log files called 
**  /test_data/domainer_embl.log and /test_data/domainer_pdb.log were written.
**  
**  The following command line would achieve the same result.
**  domainer /test_data/ .pxyz /test_data/ .dxyz /test_data/ .dent -scop 
**  /test_data/all.scop -cpdberrf /test_data/domainer_embl.log -pdberrf 
**  /test_data/domainer_pdb.log
**  
**  
**  
**  Input file format
**  The format of the protein coordinate file is described in pdbparse.c.
**  
**  
**  
**  Output file format
**  The embl-like format used for domain coordinate files is exactly the same 
**  as that used for protein coordinate files and is described in pdbparse.c.
**  
**  An excerpt of the pdb format used for domain coordinate files is shown 
**  below.  pdb format is explained on the pdb website:
**  (1) http://www.rcsb.org/pdb/docs/format/pdbguide2.2/guide2.2_frame.html
**  domainer writes the following records in pdb format (Figure 1):
**  (1)  HEADER - bibliographic information.  The text 'CLEANED-UP PDB FILE FOR 
**  SCOP DOMAIN XXXXXXX' is always given (where XXXXXXX is a 7-character domain 
**  identifier code).
**  (2)  TITLE - bibliographic information. The text ' THIS FILE IS MISSING 
**  MOST RECORDS FROM THE ORIGINAL PDB FILE' is always given.
**  (3)  COMPND - compound information.  The COMPND records from the original  
**  pdb file are given.
**  (4)  SOURCE - protein source information.  The SOURCE records from the 
**  original pdb file are given.
**  (5)  REMARK - remark records. Remark records are used for spacing. One 
**  REMARK line containing the protein resolution is always given.
**  (6)  SEQRES - protein sequence.  
**  (7)  ATOM - atomic coordinates.
**  (8)  TER - indicates the end of a chain.**  
** 
**  Excerpt of a domain coordinate file in pdb format
**  HEADER     CLEANED-UP PDB FILE FOR SCOP DOMAIN D1CS4A_                          
**  TITLE      THIS FILE IS MISSING MOST RECORDS FROM THE ORIGINAL PDB FILE         
**  COMPND     MOL_ID: 1; MOLECULE: TYPE V ADENYLATE CYCLASE;                       
**  SOURCE     MOL_ID: 1; ORGANISM_SCIENTIFIC: CANIS FAMILIARIS;                    
**  REMARK                                                                          
**  REMARK     RESOLUTION. 2.50  ANGSTROMS.                                         
**  REMARK                                                                          
**  SEQRES   1 A   52  ALA ASP ILE GLU GLY PHE THR SER LEU ALA SER GLN CYS          
**  SEQRES   2 A   52  THR ALA GLN GLU LEU VAL MET THR LEU ASN GLU LEU PHE          
**  SEQRES   3 A   52  ALA ARG PHE ASP LYS LEU ALA ALA GLU ASN HIS CYS LEU          
**  SEQRES   4 A   52  ARG ILE LYS ILE LEU GLY ASP CYS TYR TYR CYS VAL SER          
**  ATOM      1  N   ASP A   2      51.711 -11.782  62.798  1.00 51.17           N  
**  ATOM      2  CA  ASP A   2      52.810 -11.644  61.848  1.00 54.45           C  
**  ATOM      3  C   ASP A   2      54.137 -11.314  62.530  1.00 55.11           C  
**  ATOM      4  O   ASP A   2      54.175 -10.524  63.469  1.00 55.34           O  
**  ATOM      5  CB  ASP A   2      52.437 -10.555  60.831  1.00 57.50           C  
**  ATOM      6  CG  ASP A   2      53.460 -10.391  59.729  1.00 61.38           C  
**  ATOM      7  OD1 ASP A   2      54.316  -9.485  59.841  1.00 65.55           O  
**  ATOM      8  OD2 ASP A   2      53.390 -11.146  58.736  1.00 63.68           O  
**  ATOM      9  N   ILE A   3      55.216 -11.941  62.066  1.00 57.14           N  
**  ATOM     10  CA  ILE A   3      56.546 -11.705  62.624  1.00 59.46           C  
**  ATOM     11  C   ILE A   3      57.020 -10.305  62.230  1.00 60.12           C  
**  ATOM     12  O   ILE A   3      56.963  -9.927  61.060  1.00 59.12           O  
**  ATOM     13  CB  ILE A   3      57.583 -12.722  62.094  1.00 60.84           C  
**  ATOM     14  CG1 ILE A   3      57.184 -14.163  62.447  1.00 63.12           C  
**  ATOM     15  CG2 ILE A   3      58.975 -12.384  62.632  1.00 61.24           C  
**  ATOM     16  CD1 ILE A   3      57.408 -14.554  63.895  1.00 63.92           C  
**  ATOM     17  N   GLU A   4      57.492  -9.548  63.212  1.00 60.23           N  
**  ATOM     18  CA  GLU A   4      57.975  -8.198  62.971  1.00 62.14           C  
**  ATOM     19  C   GLU A   4      59.401  -8.277  62.424  1.00 60.59           C  
**  ATOM     20  O   GLU A   4      60.244  -8.972  62.987  1.00 61.84           O  
**  ATOM     21  CB  GLU A   4      57.917  -7.386  64.272  1.00 65.47           C  
**  ATOM     22  CG  GLU A   4      58.037  -5.874  64.091  1.00 70.25           C  
**  ATOM     23  CD  GLU A   4      57.588  -5.089  65.324  1.00 72.94           C  
**  ATOM     24  OE1 GLU A   4      58.262  -5.175  66.377  1.00 70.76           O  
**  ATOM     25  OE2 GLU A   4      56.555  -4.380  65.232  1.00 74.36           O  
**  ATOM     26  N   GLY A   5      59.642  -7.608  61.298  1.00 57.58           N  
**  ATOM     27  CA  GLY A   5      60.956  -7.615  60.681  1.00 56.14           C  
**  ATOM     28  C   GLY A   5      61.452  -8.993  60.265  1.00 58.03           C  
**  ATOM     29  O   GLY A   5      62.620  -9.322  60.480  1.00 57.47           O  
**  ATOM     30  N   PHE A   6      60.576  -9.789  59.649  1.00 58.00           N  
**  
**  < data ommitted for clarity >
**  
**  ATOM    354  O   CYS A  47      50.803 -16.789  58.301  1.00 50.50           O  
**  ATOM    355  CB  CYS A  47      51.409 -13.972  57.565  1.00 51.82           C  
**  ATOM    356  SG  CYS A  47      49.727 -13.277  57.723  1.00 54.53           S  
**  TER     357      CYS A  47                                                      
**  END                  
**
**
**  
**  Data files
**  No data files are used. 
**  
**  
**  
**  Diagnostic error messages
**  domainer generates a log file an excerpt of which is shown below. If 
**  there is a problem in processing a domain, three lines containing the 
**  record '//', the domain identifier code and an error message respectively
**  are written. The text 'WARN  filename not found' is given in cases where a 
**  clean coordinate file could not be found. 'ERROR filename file read error' 
**  or 'ERROR filename file write error' will be reported when an error was 
**  encountered during a file read or write respectively.  The 'ERROR Domain 
**  start found by wildcard match only' is reported when wildcard matching 
**  was needed to find the start (or end) of a domain in a pdb file (see below).
**  Various other error messages may also be given (in case of difficulty 
**  email Jon Ison, jison@hgmp.mrc.ac.uk).
**
**  Excerpt of log file
**  //
**  DS002__
**  WARN  Could not open for reading cpdb file s002.pxyz
**  //
**  DS003__
**  WARN  Could not open for reading cpdb file s003.pxyz
**
**  
**  Messages of the type:
**  //
**  D0LPC_1
**  WARN  0lpc.pxyz not found
** 
**  can appear in the log file if 
**  (i)  The domain is of a pdb file which is in holding, but has not made it
**  into the main pdb release yet.
**  (ii) The domain is of a pdb file that is now obsolete - having been 
**  replaced by a more recent entry.
**  There may be other cases too.
**
**
**  Messages of the type:
**  //
**  D1QFUL1
**  ERROR Domain start not found in ajXyzCpdbWriteDomain 
**  //
**  D1QFUL1
**  ERROR Domain end not found in ajXyzCpdbWriteDomain 
**  indicate that residues for the start or end of a domain are missing from 
**  the protein coordinate file (see 'Notes' above).
**  
**  
**  
**  Authors
**  Jon Ison (jison@hgmp.mrc.ac.uk)
**  
**  
**  
**  References
**  Please cite the authors.
**  
**  
**  
******************************************************************************/






#include "emboss.h"







/* @prog domainer *************************************************************
**
** Reads protein coordinate files and writes domain coordinate files.
**
******************************************************************************/

int main(int argc, char **argv)
{
    AjPStr   cpdb_path     =NULL;	/* Path of cpdb files */
    AjPStr   cpdb_extn     =NULL;	/* Extn. of cpdb files (protein) */
    AjPStr   pdb_extn      =NULL;	/* Extn. of pdb files */
    AjPStr   pdbscop_path  =NULL;	/* Path of pdbscop files */
    AjPStr   cpdbscop_path =NULL;	/* Path of cpdbscop files */
    AjPStr   cpdbscop_extn =NULL;	/* Extn. of cpdbscop files (domain)*/
    AjPStr   cpdb_name     =NULL;	/* Name of cpdb file */
    AjPStr   pdbscop_name  =NULL;	/* Name of pdbscop file */
    AjPStr   cpdbscop_name =NULL;	/* Name of cpdbscop file */
    AjPStr   msg           =NULL;	/* Error message */
    AjPStr   temp          =NULL;	/* Error message */

    AjPFile  scop_inf      =NULL;
    AjPFile  cpdb_inf      =NULL;
    AjPFile  pdbscop_outf  =NULL;
    AjPFile  cpdbscop_outf =NULL;
    AjPFile  errf1         =NULL;
    AjPFile  errf2         =NULL;

    AjPScop  scop=NULL;
    AjPPdb   pdb=NULL;

    
    /* Initialise strings */
    msg           = ajStrNew();
    cpdb_path     = ajStrNew();
    cpdb_extn     = ajStrNew();
    cpdbscop_extn = ajStrNew();
    pdb_extn      = ajStrNew();
    pdbscop_path  = ajStrNew();
    cpdbscop_path = ajStrNew();
    cpdb_name     = ajStrNew();
    pdbscop_name  = ajStrNew();
    cpdbscop_name = ajStrNew();
    temp          = ajStrNew();


    /* Read data from acd */
    ajNamInit("emboss");
    ajAcdInitP("domainer",argc,argv,"DOMAINATRIX"); 
    cpdb_path     = ajAcdGetString("cpdb");
    cpdb_extn     = ajAcdGetString("cpdbextn");
    cpdbscop_extn = ajAcdGetString("cpdbscopextn");
    pdb_extn      = ajAcdGetString("pdbextn");
    pdbscop_path  = ajAcdGetString("pdbscop");
    cpdbscop_path = ajAcdGetString("cpdbscop");
    scop_inf      = ajAcdGetInfile("scop");
    errf1         = ajAcdGetOutfile("pdberrf");
    errf2         = ajAcdGetOutfile("cpdberrf");
    

    /* Check directories*/
    if(!ajFileDir(&cpdb_path))
	ajFatal("Could not open cpdb directory");

    if(!ajFileDir(&pdbscop_path))
	ajFatal("Could not open pdbscop directory");

    if(!ajFileDir(&cpdbscop_path))
	ajFatal("Could not open cpdbscop directory");






    /*Start of main application loop*/
    while((ajXyzScopReadC(scop_inf, "*", &scop)))
    {
	/* Write diagnostic */
	ajFmtPrint("%S\n", scop->Entry);   

     
	/* Read clean coordinate file*/
	ajStrAss(&cpdb_name, scop->Pdb);
	ajStrToLower(&cpdb_name);
	ajStrApp(&cpdb_name, cpdb_extn);
	if(!(cpdb_inf=ajFileNewDF(cpdb_path, cpdb_name)))
	{
	    ajFmtPrintS(&msg, "Could not open for reading cpdb file %S", 
			cpdb_name);
	    ajWarn(ajStrStr(msg));
	    ajFmtPrintF(errf1, "//\n%S\nWARN  %S not found\n", 
			scop->Entry, cpdb_name);
	    ajFmtPrintF(errf2, "//\n%S\nWARN  %S not found\n", 
			scop->Entry, cpdb_name);
	    /* ajFileClose(&cpdb_inf); */
	    ajXyzScopDel(&scop);
	    continue;	    
	}
	
	
	/* Write pdb structure */
	if(!ajXyzCpdbRead(cpdb_inf, &pdb))	       
	{
	    ajFmtPrintS(&msg, "Error reading cpdb file %S", cpdb_name);
	    ajWarn(ajStrStr(msg));
	    ajFmtPrintF(errf1, "//\n%S\nERROR %S file read error\n", 
			scop->Entry, cpdb_name);
	    ajFmtPrintF(errf2, "//\n%S\nERROR %S file read error\n", 
			scop->Entry, cpdb_name);
	    ajFileClose(&cpdb_inf);
	    ajXyzScopDel(&scop);
	    ajXyzPdbDel(&pdb);
	    continue;
	}
	

	/* Open pdb format file for writing*/
	ajStrAss(&pdbscop_name, pdbscop_path);
	ajStrApp(&pdbscop_name, scop->Entry);
	ajStrToLower(&pdbscop_name);
	ajStrAppC(&pdbscop_name, ajStrStr(pdb_extn));
	if(!(pdbscop_outf=ajFileNewOut(pdbscop_name)))
	{
	    ajFmtPrintS(&msg, "Could not open for writing pdbscop file %S", 
			pdbscop_name);
	    ajWarn(ajStrStr(msg));
	    ajFmtPrintF(errf1, "//\n%S\nERROR %S file write error\n", 
			scop->Entry, pdbscop_name);
	    ajFileClose(&cpdb_inf);
/*	    ajFileClose(&pdbscop_outf); */
	    ajXyzScopDel(&scop);
	    ajXyzPdbDel(&pdb);
	    continue;
	}   	


	/* Open embl-like format file for writing*/
	ajStrAss(&cpdbscop_name, cpdbscop_path);
	ajStrApp(&cpdbscop_name, scop->Entry);
	ajStrToLower(&cpdbscop_name);
	ajStrApp(&cpdbscop_name, cpdbscop_extn);
	if(!(cpdbscop_outf=ajFileNewOut(cpdbscop_name)))
	{
	    ajFmtPrintS(&msg, "Could not open for writing cpdbscop file %S", 
			cpdbscop_name);
	    ajWarn(ajStrStr(msg));
	    ajFmtPrintF(errf2, "//\n%S\nERROR %S file write error\n", 
			scop->Entry, cpdbscop_name);
	    ajFileClose(&cpdb_inf);
	    ajFileClose(&pdbscop_outf);
	    ajXyzScopDel(&scop);
	    ajXyzPdbDel(&pdb);
	    continue;
	}   	
	
	
	/* Write domain coordinate file in pdb format */
	if(!ajXyzPdbWriteDomain(errf1, pdbscop_outf, pdb, scop))
	{
	    ajFmtPrintS(&msg, "Error writing pdbscop file %S", pdbscop_name);
	    ajWarn(ajStrStr(msg));

	    ajFileClose(&pdbscop_outf);
	    ajFmtPrintS(&temp, "rm %S", pdbscop_name);
	    ajFmtPrint("%S", temp);
	    ajSystem(&temp);

	}


	/* Write domain coordinate file in embl-like format */
	if(!ajXyzCpdbWriteDomain(errf2, cpdbscop_outf, pdb, scop))
	{
	    ajFmtPrintS(&msg, "Error writing cpdbscop file %S", 
			cpdbscop_name);
	    ajWarn(ajStrStr(msg));

	    ajFileClose(&cpdbscop_outf);
	    ajFmtPrintS(&temp, "rm %S", cpdbscop_name);
	    ajFmtPrint("%S", temp);
	    
	    ajSystem(&temp);
	}


	/* Tidy up*/
	ajFileClose(&cpdb_inf);
	ajFileClose(&pdbscop_outf);
	ajFileClose(&cpdbscop_outf);
	ajXyzScopDel(&scop);
	ajXyzPdbDel(&pdb);
    }
    /*End of main application loop*/    
    




    /*Tidy up */
    ajStrDel(&cpdb_path);
    ajStrDel(&cpdb_extn);
    ajStrDel(&cpdbscop_extn);
    ajStrDel(&pdb_extn);
    ajStrDel(&pdbscop_path);
    ajStrDel(&cpdbscop_path);
    ajStrDel(&cpdb_name);
    ajStrDel(&pdbscop_name);
    ajStrDel(&cpdbscop_name);
    ajStrDel(&msg);
    ajStrDel(&temp);
    ajFileClose(&scop_inf);
    ajFileClose(&errf1);
    ajFileClose(&errf2);


    /* Bye Bye */
    ajExit();
    return 0;
}	
